[theme]
# Color principal (Botones, deslizadores, enlaces, pestañas activas)
# Usamos un azul profundo tipo corporativo
primaryColor = "#00205B"

# Color de fondo principal de la aplicación
backgroundColor = "#FFFFFF"

# Color de la barra lateral y bloques de fondo
# Un gris azulado muy suave para diferenciar secciones
secondaryBackgroundColor = "#a8cff7ff"

# Color del texto
textColor = "#262730"

# Fuente (sans serif es la estándar moderna tipo Arial/Helvetica)
font = "sans serif"